site_name: Make Us Rich
site_description: Make Us Rich project
repo_name: ChainYo/make-us-rich
repo_url: https://github.com/ChainYo/make-us-rich
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  palette:
    - scheme: slate
      primary: orange
      accent: yellow
  features:
    - navigation.tracking

nav:
- MakeUsRich: index.md
- Components:
  - Training: training.md
  - Serving: serving.md
  - Interface: interface.md
- API: api.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
  - search:
      lang: en
  - mkdocstrings:
      handlers:
        python:
          selection:
            docstring_style: numpy
  - git-revision-date
