site_name: Make Us Rich
site_description: Make Us Rich project
repo_name: ChainYo/make-us-rich
repo_url: https://github.com/ChainYo/make-us-rich
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: orange
      accent: red
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      primary: orange
      accent: red
  features:
    - navigation.tracking

nav:
- MakeUsRich: index.md
- Components:
  - Training: training.md
  - Serving: serving.md
  - Interface: interface.md
- API: 
  - api.md
  - CLI: api/cli.md
  - client: api/client.md
  - interface: api/interface.md
  - pipelines: 
    - api/pipelines.md
    - fetching: api/pipelines/fetching.md
    - preprocessing: api/pipelines/preprocessing.md
    - training: api/pipelines/training.md
    - converting: api/pipelines/converting.md
    - exporting: api/pipelines/exporting.md
  - serving: api/serving.md
  - utils: api/utils.md
  - worker: api/worker.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
  - search:
      lang: en
  - mkdocstrings:
      handlers:
        python:
          selection:
            docstring_style: numpy
  - git-revision-date
