site_name: Make Us Rich
site_description: Make Us Rich project
repo_name: ChainYo/make-us-rich
repo_url: https://github.com/ChainYo/make-us-rich
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  palette:
    - scheme: slate
      primary: orange
      accent: yellow

plugins:
- search
- mkdocstrings
- git-revision-date
