target_column: 'close'
sequence_length: 60
val_size: 0.2
training:
  train_batch_size: 16
  val_batch_size: 1
  train_workers: 2
  val_workers: 1
  max_epochs: 100
  hidden_size: 128
  number_of_features: 9
  number_of_layers: 2
  dropout_rate: 0.2
  learning_rate: 0.0001
  log_n_steps: 2
  run_on_gpu: True
  dir_path: "data/06_models/checkpoints"
