fetching:
  interval: "1h"
  start_date: "365 days ago UTC"
target_column: "close"
sequence_length: 120
val_size: 0.2
dir_path: "data/06_models/"
training:
  train_batch_size: 16
  val_batch_size: 1
  train_workers: 2
  val_workers: 1
  max_epochs: 100
  hidden_size: 128
  number_of_features: 9
  number_of_layers: 2
  dropout_rate: 0.2
  learning_rate: 0.0001
  log_n_steps: 2
  run_on_gpu: True # False if running on CPU
conversion:
  batch_size: 1
